resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
    tag: latest

resources:
- name: pull-request
  type: pull-request
  check_every: 5s
  webhook_token: test-token
  source:
    repository: GavinFigueroa/test
    access_token: 84d3df994b394062bd47d05993fd856c310a40be
    v3_endpoint: https://api.github.com
    v4_endpoint: https://api.github.com/graphql

jobs:
- name: automerge
  plan:
  - get: pull-request
    trigger: true
  - task: run
    file: pull-request/run.yml